<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMUBwjp\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMUBwjp/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOMUBwjp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOMUBwjp\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerOMUBwjp\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'OMUBwjp',
    'container.build_id' => 'b5134754',
    'container.build_time' => 1549981332,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMUBwjp');
