<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKJYGBPi\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKJYGBPi/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKJYGBPi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKJYGBPi\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerKJYGBPi\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'KJYGBPi',
    'container.build_id' => '725ff2d6',
    'container.build_time' => 1548436633,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKJYGBPi');
