<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AdministrateurController::inscriptionDesAdministrateurs' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController::inscriptionDesJeunes' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController::inscriptionDesPartenaires' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController::modificationDesInformationsAdministrateur' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController::modificationDesOffres' => array('privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true),
    'App\\Controller\\AdministrateurController::modificationDesPartenaires' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\PartenaireController::ajoutOffres' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\PartenaireController::listeOffres' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\RegistrationController::register' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\SecurityController::login' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
    'App\\Controller\\AdministrateurController:inscriptionDesAdministrateurs' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController:inscriptionDesJeunes' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController:inscriptionDesPartenaires' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController:modificationDesInformationsAdministrateur' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\AdministrateurController:modificationDesOffres' => array('privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true),
    'App\\Controller\\AdministrateurController:modificationDesPartenaires' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\PartenaireController:ajoutOffres' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\PartenaireController:listeOffres' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\RegistrationController:register' => array('privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true),
    'App\\Controller\\SecurityController:login' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
)));
