<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-http\\AccessMapInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-http\\AccessMap.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcherInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$a = new \Symfony\Component\HttpFoundation\RequestMatcher('^/offres');

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/administrateur/inscription'), array(0 => 'ROLE_ADMINISTRATEUR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/jeune/inscription'), array(0 => 'ROLE_ADMINISTRATEUR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/partenaire/inscription'), array(0 => 'ROLE_ADMINISTRATEUR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/partenaire/profil'), array(0 => 'ROLE_PARTENAIRE'), NULL);
$instance->add($a, array(0 => 'ROLE_PARTENAIRE'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/jeune/profil'), array(0 => 'ROLE_JEUNE'), NULL);
$instance->add($a, array(0 => 'ROLE_JEUNE'), NULL);

return $instance;
