<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGljlxAW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGljlxAW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGljlxAW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGljlxAW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGljlxAW\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'GljlxAW',
    'container.build_id' => '41199420',
    'container.build_time' => 1553273808,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGljlxAW');
