<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvkfnpO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvkfnpO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvkfnpO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvkfnpO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZvkfnpO\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ZvkfnpO',
    'container.build_id' => '8c8d70f2',
    'container.build_time' => 1554113656,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvkfnpO');
